name: dnie_tools
description: Flutter DNIe tools
version: 0.0.1
homepage: https://github.com/sergiocasero

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sergiocasero.dnie_tools
        pluginClass: DnieToolsPlugin
      # ios:
      #   pluginClass: DnieToolsFlutterPlugin
